### PR TITLE
Added title to the home page and made it responsive

### PR DESCRIPTION
**Pull request by ojasaklechayt**
Issue Number: #49 

# Description:
I have done the following things:
    1. Added H1 tag which says " Welcome to Jarvis " which improves the UI
    2. Made it basic responsive
 
# Screenshot: 
image

# Checklist:

 - [x] My code adheres to the established style guidelines of the project.
 - [x] I have included comments in areas that may be difficult to understand.
 - [x] My changes have not introduced any new warnings.
 - [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by J0SAL** [comment]
Again the code is not updated with the latest main branch (I think you have incorrectly resolved the merge conflicts) , if you are finding it difficult contact @Abhijit25Mishra on Discord

**Comment by Abhijit25Mishra** [comment]
@ojasaklechayt @J0SAL It will be better if you mention me here then reach on discord as it notifies me via mail.

**Comment by Abhijit25Mishra** [comment]
Hey @ojasaklechayt there is a template PR for this repo. Please use that.

**Comment by J0SAL** [comment]
Closing this PR, as there is no update

**Pull request closed without merging**
