### PR TITLE
Add error 404 page

### LINKED ISSUE #127: Want to add error 404 page
### Is your feature request related to a problem? Please describe.

I want to add a new error 404 page with awesome UI. Please assign me this issue, I want to work on it under GSSOC 2023

### Describe the solution you'd like

My design looks like this 
image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by silky-modi22**
Resolves #127 

## Description

I add a error 404 page

## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by silky-modi22** [comment]
@J0SAL Please review my PR

**Comment by Abhijit25Mishra** [comment]
@silky-modi22  does this redirects unknown requests to this 404 page as well ? i dont think you have done any routing.

**Comment by J0SAL** [comment]
> @silky-modi22 does this redirects unknown requests to this 404 page as well ? i dont think you have done any routing.

@silky-modi22 you can refer to the following page, [link](https://www.geeksforgeeks.org/how-to-create-a-custom-error-page-in-next-js/) to see how custom error page can be added to nextJS

**Comment by silky-modi22** [comment]
Thank you sharing. I'll update you soon

**Comment by Abhijit25Mishra** [comment]
@silky-modi22  update ?

**Pull request closed without merging**
