### PR TITLE
feat(login): added network/chain details

### LINKED ISSUE #110: Add netword/chain details on homepage
### Is your feature request related to a problem? Please describe.

Currently while we visit homepage theres only one button is there for connect wallet which might not be the best and should be changed

### Describe the solution you'd like

And i think details like 
Network / Chain or if we are using testnet such as sepolia should be present in homepage if not on homepage on other page 
also with the details of networks and specially which testnet to user will be very helpful to first time visitor 
and can prevent unusual bugs

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shobhitexe**
Resolves #110 

## Description

Added details of which network we are using currently and with a message of "support for more network is comming"

## Screenshots

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by J0SAL** [comment]
@shobhitexe, Well, this isn't what we discussed. 
The issue was about having a dropdown through which users can change the networks, after logging in.

**Comment by shobhitexe** [comment]
> @shobhitexe, Well, this isn't what we discussed. The issue was about having a dropdown through which users can change the networks, after logging in.

i request you to read that issue again, 
I mentioned that there should be information about the chain on the homepage or another relevant page. I'm not sure how you interpreted it as a dropdown requirement.

image

**Comment by J0SAL** [comment]
> mentioned that there should be information about the chain on the homepage or another relevant page. I'm not sure how you interpreted it as a dropdown requirement.

@shobhitexe Didn't you check my comment? 

image

**Comment by shobhitexe** [comment]
> > mentioned that there should be information about the chain on the homepage or another relevant page. I'm not sure how you interpreted it as a dropdown requirement.
> 
> @shobhitexe Didn't you check my comment?
> 
> image

I believe there may have been a misunderstanding. I will go ahead and create a new pull request specifically for the dropdown feature.

**Comment by J0SAL** [comment]
@shobhitexe  Just to add more references,
user should get an option to switch chains when he'll click on the profile button, UI similar to the image below, 
image

it's from https://testnets.opensea.io/account

**Pull request closed without merging**
