### PR TITLE
Update PageNavbar.tsx

### LINKED ISSUE #102: Tha Navbar is not responsive for some screen sizes.
### Description

Please assign me this issue, I would like to work on it. (with the label of GSSoC).

### Screenshots

#Screenshot 

https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/132553685/d287b0d4-3417-4808-95d7-70d96978db98

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shrutigolwalk0109**
I have added some style to this file to make it responsive for mobile screens and some other screen sizes.

Resolves #102 

## Screenshots/ video 

https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/132553685/5c9760f4-dd58-4328-abb4-eea1638edd3a

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by J0SAL** [comment]
@Abhijit25Mishra can you review this

**Comment by shrutigolwalk0109** [comment]
Please review it. @Abhijit25Mishra  @J0SAL

**Comment by Abhijit25Mishra** [comment]
@J0SAL @shrutigolwalk0109 I am actually traveling this weekend and dont have access to a laptop. I will do this tomorrow morning. Sorry for the inconvenience.

**Review by Abhijit25Mishra — APPROVED** [review]
seems fine

**Comment by Abhijit25Mishra** [comment]
Hey @shrutigolwalk0109  there is a template PR for this repo. Please use that.
https://github.com/J0SAL/Decentralized-Expense-Tracker/blob/a71bf039e1f6e4b31ee8058662848d451e302a3c/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Abhijit25Mishra** [comment]
@J0SAL this is a single line change nothing much to review here.

**Pull request closed without merging**
